#!/usr/bin/perl

$header = <>;
$header = <>;

# 982324

$min = -1.523;
$max = 4.418;

$width = 14000;
$height = 20;

printf("%.3f %.3f %.3f setrgbcolor\n", 65/255, 136/255, 132/255);
print "newpath 0 0 moveto $width 0 lineto $width $height lineto 0 $height lineto closepath fill\n";

print "0 setlinewidth\n";

printf("%.3f %.3f %.3f setrgbcolor\n", 0/255, 66/255, 220/255);

print "newpath 0 $height moveto\n";
$within = 1;

while (<>) {
	chomp;
	($date, $level) = split(/,/);

	$year = $date;
	$year =~ s/-.*//;

	$x{$year} += $seq / 982324 * $width;
	$y{$year} += $level;
	$count{$year}++;

	$avg += ($level - $min) * $height / ($max - $min);
	$count++;

	printf("%.6f %.6f %s\n",
		$seq++ / 982324 * $width,
		($level - $min) * $height / ($max - $min),
		$within ? "lineto" : "moveto");

	if ($seq % 200 == 0) {
		printf("%.6f %.6f %s\n",
			$seq / 982324 * $width,
			$height,
			"lineto closepath fill");

		printf("newpath %.6f %.6f %s\n",
			$seq / 982324 * $width,
			$height,
			"moveto ");

		printf("%.6f %.6f %s\n",
			$seq / 982324 * $width,
			($level - $min) * $height / ($max - $min),
			"lineto ");
	}
}

if ($within) {
	printf("%.6f %.6f %s\n",
		$seq / 982324 * $width,
		$height,
		"lineto closepath fill");

	$within = 0;
}

print "0 setlinewidth\n";

$maxavg = $y{1910} / $count{1910};
$minavg = $y{1910} / $count{1910};

for $year (sort(keys(%count))) {
	$v = $y{$year} / $count{$year};

	if ($v > $maxavg) {
		$maxavg = $v;
	}
	if ($v < $minavg) {
		$minavg = $v;
	}
}

printf("%.3f %.3f %.3f setrgbcolor\n", 235/255, 124/255, 50/255);

for $year (sort(keys(%count))) {
	printf("%.6f %.6f %s %% %s\n",
		$x{$year} / $count{$year},
		($y{$year} / $count{$year} - $minavg) * $height / ($maxavg - $minavg),
		$within ? "lineto" : "moveto",
		$year);

	$within = 1;
}

print "stroke\n";
