#!/usr/bin/perl

$header = <>;
$header = <>;

# 982324

$min = -1.523;
$max = 4.418;

$width = 14000;
$height = 20;

printf("%.3f %.3f %.3f setrgbcolor\n", 81/255, 178/255, 210/255);
print "newpath 0 0 moveto $width 0 lineto $width $height lineto 0 $height lineto closepath fill\n";

$bottom .= "0 setlinewidth\n";

$bottom .= sprintf("%.3f %.3f %.3f setrgbcolor\n", 237/255, 130/255, 51/255);

#print "newpath 0 $height moveto\n";
#$within = 1;

while (<>) {
	chomp;
	($date, $level) = split(/,/);

	$year = $date;
	$year =~ s/-.*//;

	$x{$year} += $seq / 982324 * $width;
	$y{$year} += $level;
	$count{$year}++;

	$avg += ($level - $min) * $height / ($max - $min);
	$count++;

	$bottom .= sprintf("%.6f %.6f %s\n",
		$seq++ / 982324 * $width,
		($level - $min) * $height / ($max - $min),
		$within ? "lineto" : "moveto");
	$within = 1;

	if ($seq % 200 == 0) {
		$bottom .= "stroke\n";

		$bottom .= sprintf("%.6f %.6f %s\n",
			$seq++ / 982324 * $width,
			($level - $min) * $height / ($max - $min),
			"moveto");
	}
}

if ($within) {
	$bottom .= "stroke\n";

	$within = 0;
}

print "0 setlinewidth\n";

$maxavg = $y{1910} / $count{1910};
$minavg = $y{1910} / $count{1910};

for $year (sort(keys(%count))) {
	$v = $y{$year} / $count{$year};

	if ($v > $maxavg) {
		$maxavg = $v;
	}
	if ($v < $minavg) {
		$minavg = $v;
	}
}

printf("%.3f %.3f %.3f setrgbcolor\n", 63/255, 136/255, 191/255);

print "newpath 0 0 moveto\n";
$within = 1;
for $year (sort(keys(%count))) {
	printf("%.6f %.6f %s %% %s\n",
		$x{$year} / $count{$year},
		($y{$year} / $count{$year} - $minavg) * $height / ($maxavg - $minavg),
		$within ? "lineto" : "moveto",
		$year);

	$within = 1;
}

printf("%.6f %.6f %s\n",
	$seq / 982324 * $width,
	0,
	"lineto closepath fill\n");


print $bottom;
